name = "JuliaPOMDP"
uuid = "24473b4a-b5e7-11e8-1723-151708197492"
repo = "http://github.com/JuliaPOMDP/Registry.git"

description = """
Registry for POMDPs.jl solvers and models
"""

[packages]
041f53e1-e4f8-54ec-814d-e9e995aa38d4 = { name = "LaserTag", path = "L/LaserTag" }
0729bffe-8e6b-52fa-a3fa-893719b744f4 = { name = "POMDPToolbox", path = "P/POMDPToolbox" }
08074719-1b2a-587c-a292-00f91cc44415 = { name = "POMDPModelTools", path = "P/POMDPModelTools" }
13b007ba-0ca8-5af2-9adf-bc6a6301e25a = { name = "FIB", path = "F/FIB" }
182e52fb-cfd0-5e46-8c26-fd0667c990f4 = { name = "POMDPPolicies", path = "P/POMDPPolicies" }
2535ab7d-5cd8-5a07-80ac-9b1792aadce3 = { name = "JSON2", path = "J/JSON2" }
30d33687-f7ed-5b0d-8b26-3dc9b7abd572 = { name = "MCVI", path = "M/MCVI" }
355abbd5-f08e-5560-ac9e-8b5f2592a0ca = { name = "POMDPModels", path = "P/POMDPModels" }
3aa3ecc9-5a5d-57c8-8188-3e47bd8068d2 = { name = "QMDP", path = "Q/QMDP" }
3b430cce-3194-5812-b203-bf9e73c3e836 = { name = "AEMS", path = "A/AEMS" }
4b033969-44f6-5439-a48b-c11fa3648068 = { name = "DiscreteValueIteration", path = "D/DiscreteValueIteration" }
4c53ee00-974c-466f-8fa5-8dd73959bbab = { name = "POMCPOW", path = "P/POMCPOW" }
5cbb95a3-277b-5373-895a-7e14bd91b3cc = { name = "ContinuumWorld", path = "C/ContinuumWorld" }
61d90e0f-e114-555e-ac52-39dfb47a3ef9 = { name = "GeoJSON", path = "G/GeoJSON" }
682c06a0-de6a-54ab-a142-c8b1cf79cde6 = { name = "JSON", path = "J/JSON" }
7d188eb4-7ad8-530c-ae41-71a32a6d4692 = { name = "JSONSchema", path = "J/JSONSchema" }
92e6a534-49c2-5324-9027-86e3c861ab81 = { name = "POMDPTesting", path = "P/POMDPTesting" }
9b8beb19-0777-58c6-920b-28f749fee4d3 = { name = "JSONWebTokens", path = "J/JSONWebTokens" }
9cf5b727-2e06-5671-8c87-8c6b0f729d5d = { name = "POMDPFiles", path = "P/POMDPFiles" }
a40420fb-f401-52da-a663-f502e5b95060 = { name = "LocalApproximationValueIteration", path = "L/LocalApproximationValueIteration" }
a575d7f4-a5df-53f5-8ba4-9d691c1ba8ff = { name = "POMDPSolve", path = "P/POMDPSolve" }
a93abf59-7444-517b-a68a-c42f96afdd7d = { name = "POMDPs", path = "P/POMDPs" }
c6f6ee83-58c6-5336-a19f-2c76817e1af6 = { name = "POMDPXFiles", path = "P/POMDPXFiles" }
c8b314e2-9260-5cf8-ae76-3be7461ca6d0 = { name = "ParticleFilters", path = "P/ParticleFilters" }
cd197ee6-b873-11e8-324e-2bd8ebd9d51c = { name = "BlinkPOMDPSimulator", path = "B/BlinkPOMDPSimulator" }
cef570c6-3a94-5604-96b7-1a5e143043f2 = { name = "SARSOP", path = "S/SARSOP" }
d721219e-3fc6-5570-a8ef-e5402f47c49e = { name = "BasicPOMCP", path = "B/BasicPOMCP" }
d96c9ae4-3372-47d5-8a88-316ae77be8cf = { name = "ARDESPOT", path = "A/ARDESPOT" }
df77095f-98f0-51e5-a706-d0ff5a5ad33f = { name = "TabularTDLearning", path = "T/TabularTDLearning" }
e0d0a172-29c6-5d4e-96d0-f262df5d01fd = { name = "POMDPSimulators", path = "P/POMDPSimulators" }
e12ccd36-dcad-5f33-8774-9175229e7b33 = { name = "MCTS", path = "M/MCTS" }
fc18253b-5e1b-504c-a4a2-9ece4944c004 = { name = "LazyJSON", path = "L/LazyJSON" }
