name = "JuliaPOMDP"
uuid = "24473b4a-b5e7-11e8-1723-151708197492"
repo = "http://github.com/JuliaPOMDP/Registry.git"

description = """
Registry for POMDPs.jl solvers and models
"""

[packages]
041f53e1-e4f8-54ec-814d-e9e995aa38d4 = { name = "LaserTag", path = "L/LaserTag" }
13b007ba-0ca8-5af2-9adf-bc6a6301e25a = { name = "FIB", path = "F/FIB" }
277f244e-4908-11e9-33c2-5d5365097ef8 = { name = "GlobalApproximationValueIteration", path = "G/GlobalApproximationValueIteration" }
3065fe53-3878-5aed-aae7-ab641be43734 = { name = "RLInterface", path = "R/RLInterface" }
30d33687-f7ed-5b0d-8b26-3dc9b7abd572 = { name = "MCVI", path = "M/MCVI" }
3aa3ecc9-5a5d-57c8-8188-3e47bd8068d2 = { name = "QMDP", path = "Q/QMDP" }
3b430cce-3194-5812-b203-bf9e73c3e836 = { name = "AEMS", path = "A/AEMS" }
4b033969-44f6-5439-a48b-c11fa3648068 = { name = "DiscreteValueIteration", path = "D/DiscreteValueIteration" }
4c53ee00-974c-466f-8fa5-8dd73959bbab = { name = "POMCPOW", path = "P/POMCPOW" }
5cbb95a3-277b-5373-895a-7e14bd91b3cc = { name = "ContinuumWorld", path = "C/ContinuumWorld" }
63556450-714a-11e9-08e1-e368b701e279 = { name = "DroneSurveillance", path = "D\\DroneSurveillance" }
7f35509c-0cb9-11e9-0708-2928828cdbb7 = { name = "POMDPGifs", path = "P/POMDPGifs" }
82ee451e-1805-57fd-b4f9-e90c19bcb3e9 = { name = "IncrementalPruning", path = "I/IncrementalPruning" }
9cf5b727-2e06-5671-8c87-8c6b0f729d5d = { name = "POMDPFiles", path = "P/POMDPFiles" }
a40420fb-f401-52da-a663-f502e5b95060 = { name = "LocalApproximationValueIteration", path = "L/LocalApproximationValueIteration" }
a575d7f4-a5df-53f5-8ba4-9d691c1ba8ff = { name = "POMDPSolve", path = "P/POMDPSolve" }
abefb91b-a28c-5ab9-9bd9-026e532d7b0e = { name = "POMDPModelChecking", path = "P\\POMDPModelChecking" }
c6f6ee83-58c6-5336-a19f-2c76817e1af6 = { name = "POMDPXFiles", path = "P/POMDPXFiles" }
cd197ee6-b873-11e8-324e-2bd8ebd9d51c = { name = "BlinkPOMDPSimulator", path = "B/BlinkPOMDPSimulator" }
cef570c6-3a94-5604-96b7-1a5e143043f2 = { name = "SARSOP", path = "S/SARSOP" }
d6851e30-d4b8-11e9-06de-0b345e2a813d = { name = "BeliefGridValueIteration", path = "B\\BeliefGridValueIteration" }
d721219e-3fc6-5570-a8ef-e5402f47c49e = { name = "BasicPOMCP", path = "B/BasicPOMCP" }
d96c9ae4-3372-47d5-8a88-316ae77be8cf = { name = "ARDESPOT", path = "A/ARDESPOT" }
de008ff0-c357-11e8-3329-7fe746fe836e = { name = "RockSample", path = "R/RockSample" }
de0a67f4-c691-11e8-0034-5fc6e16e22d3 = { name = "DeepQLearning", path = "D/DeepQLearning" }
df77095f-98f0-51e5-a706-d0ff5a5ad33f = { name = "TabularTDLearning", path = "T/TabularTDLearning" }
e12ccd36-dcad-5f33-8774-9175229e7b33 = { name = "MCTS", path = "M/MCTS" }
