name = "JuliaPOMDP"
uuid = "24473b4a-b5e7-11e8-1723-151708197492"
repo = "git@github.com:JuliaPOMDP/Registry.git"

description = """
Registry for POMDPs.jl solvers and models"""

[packages]
4b033969-44f6-5439-a48b-c11fa3648068 = { name = "DiscreteValueIteration", path = "D/DiscreteValueIteration" }
df77095f-98f0-51e5-a706-d0ff5a5ad33f = { name = "TabularTDLearning", path = "T/TabularTDLearning" }
